# Generated by Django 4.1.2 on 2022-10-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='birth',
            field=models.CharField(max_length=20),
        ),
    ]
